DROP TABLE IF EXISTS riesgos;

CREATE TABLE IF NOT EXISTS institucion_categorias (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    activo BOOLEAN DEFAULT TRUE,
    creador VARCHAR(100),
    creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modificador VARCHAR(100),
    modificacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS instituciones (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_categoria_id INTEGER REFERENCES institucion_categorias(id),
    nombre VARCHAR(200) NOT NULL,
    siglas VARCHAR(50),
    observaciones TEXT,
    activo BOOLEAN DEFAULT TRUE,
    creador VARCHAR(100),
    creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modificador VARCHAR(100),
    modificacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS usuarios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id INTEGER NOT NULL,
    usuario VARCHAR(100) NOT NULL,
    clave VARCHAR(255),
    descripcion TEXT,
    celular VARCHAR(20),
    correo VARCHAR(150),
    nombres VARCHAR(100),
    apellidos VARCHAR(100),
    cedula VARCHAR(20),
    aprobado BOOLEAN DEFAULT FALSE,
    activo BOOLEAN DEFAULT TRUE,
    creador VARCHAR(100),
    creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modificador VARCHAR(100),
    modificacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS provincias (
    id INTEGER PRIMARY KEY,
    dpa VARCHAR(2) NOT NULL UNIQUE,
    nombre VARCHAR(100) NOT NULL,
    abreviatura VARCHAR(10),
    activo BOOLEAN DEFAULT TRUE,
    creador VARCHAR(100),
    creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modificador VARCHAR(100),
    modificacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    googlecode VARCHAR(5)
);

CREATE TABLE IF NOT EXISTS cantones (
    id INTEGER PRIMARY KEY,
    provincia_id INTEGER NOT NULL REFERENCES provincias(id),
    dpa VARCHAR(5) NOT NULL UNIQUE,
    nombre VARCHAR(100) NOT NULL,
    abreviatura VARCHAR(10),
    activo BOOLEAN DEFAULT TRUE,
    creador VARCHAR(100),
    creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modificador VARCHAR(100),
    modificacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    latitud_centro NUMERIC(15,12) DEFAULT 0,
    longitud_centro NUMERIC(15,12) DEFAULT 0
);

CREATE TABLE IF NOT EXISTS parroquias (
    id INTEGER PRIMARY KEY,
    provincia_id INTEGER NOT NULL REFERENCES provincias(id),
    canton_id INTEGER NOT NULL,
    dpa VARCHAR(9) NOT NULL UNIQUE,
    nombre VARCHAR(100) NOT NULL,
    abreviatura VARCHAR(10),
    activo BOOLEAN DEFAULT TRUE,
    creador VARCHAR(100),
    creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modificador VARCHAR(100),
    modificacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    latitud_centro NUMERIC(15,12) DEFAULT 0,
    longitud_centro NUMERIC(15,12) DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.zonas (
    id BIGINT PRIMARY KEY,
    provincia_id INTEGER NOT NULL REFERENCES provincias(id),
    canton_id INTEGER NOT NULL REFERENCES cantones(id),
    parroquia_id INTEGER NOT NULL REFERENCES parroquias(id),
    dpa VARCHAR(11) NOT NULL UNIQUE,
    nombre VARCHAR(100) NOT NULL,
    abreviatura VARCHAR(10),
    activo BOOLEAN DEFAULT TRUE,
    creador VARCHAR(100),
    creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modificador VARCHAR(100),
    modificacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.emergencias (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    antecedentes TEXT,
    situacion_actual TEXT,
    nivel_afectacion_id INTEGER,
    nivel_alerta_id INTEGER,
    fecha_inicio TIMESTAMP,
    fecha_fin TIMESTAMP,
    etapa_id INTEGER,
    provincias_impactadas INTEGER,
    cantones_impactados INTEGER,
    parroquias_impactadas INTEGER,
    eventos_adversos INTEGER,
    declaratorias_emergencia INTEGER,
    declaratorias_desastre INTEGER,
    declaratorias_catastrofe INTEGER,
    costo_estimado_danos NUMERIC(12,2),
    activo BOOLEAN DEFAULT TRUE,
    creador VARCHAR(100),
    creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modificador VARCHAR(100),
    modificacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    evento_tipo_id INTEGER,
    dashboard TEXT
);

CREATE TABLE IF NOT EXISTS public.infraestructura_tipos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emergencia_id INTEGER REFERENCES public.emergencias(id),
    nombre TEXT NOT NULL,
    siglas TEXT,
    descripcion TEXT,
    activo BOOLEAN DEFAULT TRUE,
    creador TEXT,
    creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modificador TEXT,
    modificacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.infraestructuras (
    id BIGINT PRIMARY KEY,
    provincia_id INTEGER NOT NULL,
    canton_id INTEGER NOT NULL,
    parroquia_id INTEGER NOT NULL,
    zona_id BIGINT NOT NULL,
    dpa VARCHAR(15) NOT NULL,
    infraestructura_tipo_id INTEGER REFERENCES public.infraestructura_tipos(id),
    nombre TEXT,
    direccion TEXT,
    longitud NUMERIC(15,12) DEFAULT 0,
    latitud NUMERIC(15,12) DEFAULT 0,
    activo BOOLEAN DEFAULT TRUE,
    creador TEXT,
    creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modificador TEXT,
    modificacion TIMESTAMP,
    CONSTRAINT ck_infraestructuras_id_dpa CHECK (id = dpa::BIGINT)
);

CREATE TABLE IF NOT EXISTS public.eventos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emergencia_id INTEGER NOT NULL,
    provincia_id INTEGER NOT NULL,
    canton_id INTEGER NOT NULL,
    parroquia_id INTEGER NOT NULL,
    infraestructura_id BIGINT NOT NULL DEFAULT 0,
    afectacion_variable_id INTEGER NOT NULL DEFAULT 0,
    sector VARCHAR(1000) NOT NULL,
    evento_fecha TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    longitud NUMERIC(15,12) DEFAULT 0,
    latitud NUMERIC(15,12) DEFAULT 0,
    evento_tipo_id INTEGER NOT NULL,
    evento_subtipo_id INTEGER,
    evento_causa_id INTEGER NOT NULL,
    evento_origen_id INTEGER NOT NULL,
    evento_atencion_estado_id INTEGER,
    alto_impacto BOOLEAN NOT NULL DEFAULT FALSE,
    descripcion VARCHAR(5000),
    situacion VARCHAR(12000),
    activo BOOLEAN DEFAULT TRUE,
    creador TEXT,
    creacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    modificador TEXT,
    modificacion TIMESTAMP WITH TIME ZONE,
    evento_id_redm INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.afectacion_variable_registros (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emergencia_id INTEGER NOT NULL,
    provincia_id INTEGER NOT NULL,
    canton_id INTEGER NOT NULL,
    parroquia_id INTEGER NOT NULL,
    evento_id INTEGER NOT NULL,
    afectacion_variable_id INTEGER NOT NULL,
    cantidad INTEGER NOT NULL,
    costo INTEGER NOT NULL,
    activo BOOLEAN DEFAULT TRUE,
    creador TEXT,
    creacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    modificador TEXT,
    modificacion TIMESTAMP WITH TIME ZONE,
    evento_id_redm INTEGER NOT NULL DEFAULT 0,
    afectacion_id_redm INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.afectacion_variable_registro_detalles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    afectacion_variable_registro_id INTEGER NOT NULL,
    infraestructura_id BIGINT NOT NULL,
    costo INTEGER NOT NULL,
    activo BOOLEAN DEFAULT TRUE,
    creador TEXT,
    creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modificador TEXT,
    modificacion TIMESTAMP
);
