DROP TABLE IF EXISTS riesgos;

CREATE TABLE IF NOT EXISTS institucion_categorias (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    activo BOOLEAN DEFAULT TRUE,
    creador VARCHAR(100),
    creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modificador VARCHAR(100),
    modificacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS instituciones (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_categoria_id INTEGER REFERENCES institucion_categorias(id),
    nombre VARCHAR(200) NOT NULL,
    siglas VARCHAR(50),
    observaciones TEXT,
    activo BOOLEAN DEFAULT TRUE,
    creador VARCHAR(100),
    creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modificador VARCHAR(100),
    modificacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS usuarios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id INTEGER NOT NULL,
    usuario VARCHAR(100) NOT NULL,
    clave VARCHAR(255),
    descripcion TEXT,
    celular VARCHAR(20),
    correo VARCHAR(150),
    nombres VARCHAR(100),
    apellidos VARCHAR(100),
    cedula VARCHAR(20),
    aprobado BOOLEAN DEFAULT FALSE,
    activo BOOLEAN DEFAULT TRUE,
    creador VARCHAR(100),
    creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modificador VARCHAR(100),
    modificacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
