DROP TABLE IF EXISTS riesgos;

CREATE TABLE IF NOT EXISTS institucion_categorias (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    activo BOOLEAN DEFAULT TRUE,
    creador VARCHAR(100),
    creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modificador VARCHAR(100),
    modificacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS instituciones (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_categoria_id INTEGER REFERENCES institucion_categorias(id),
    nombre VARCHAR(200) NOT NULL,
    siglas VARCHAR(50),
    observaciones TEXT,
    activo BOOLEAN DEFAULT TRUE,
    creador VARCHAR(100),
    creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modificador VARCHAR(100),
    modificacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS usuarios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id INTEGER NOT NULL,
    usuario VARCHAR(100) NOT NULL,
    clave VARCHAR(255),
    descripcion TEXT,
    celular VARCHAR(20),
    correo VARCHAR(150),
    nombres VARCHAR(100),
    apellidos VARCHAR(100),
    cedula VARCHAR(20),
    aprobado BOOLEAN DEFAULT FALSE,
    activo BOOLEAN DEFAULT TRUE,
    creador VARCHAR(100),
    creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modificador VARCHAR(100),
    modificacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS provincias (
    id INTEGER PRIMARY KEY,
    dpa VARCHAR(2) NOT NULL UNIQUE,
    nombre VARCHAR(100) NOT NULL,
    abreviatura VARCHAR(10),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creador VARCHAR(100),
    creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modificador VARCHAR(100),
    modificacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cantones (
    id INTEGER PRIMARY KEY,
    provincia_id INTEGER NOT NULL REFERENCES provincias(id),
    dpa VARCHAR(5) NOT NULL UNIQUE,
    nombre VARCHAR(100) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creador VARCHAR(100),
    creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modificador VARCHAR(100),
    modificacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS parroquias (
    id INTEGER PRIMARY KEY,
    provincia_id INTEGER NOT NULL REFERENCES provincias(id),
    canton_id INTEGER NOT NULL REFERENCES cantones(id),
    dpa VARCHAR(9) NOT NULL UNIQUE,
    nombre VARCHAR(100) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creador VARCHAR(100),
    creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modificador VARCHAR(100),
    modificacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.zonas (
    id BIGINT PRIMARY KEY,
    provincia_id INTEGER NOT NULL REFERENCES provincias(id),
    canton_id INTEGER NOT NULL REFERENCES cantones(id),
    parroquia_id INTEGER NOT NULL REFERENCES parroquias(id),
    dpa VARCHAR(11) NOT NULL UNIQUE,
    nombre VARCHAR(100) NOT NULL,
    abreviatura VARCHAR(10),
    activo BOOLEAN DEFAULT TRUE,
    creador VARCHAR(100),
    creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modificador VARCHAR(100),
    modificacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.infraestructuras (
    id BIGINT PRIMARY KEY,
    provincia_id INTEGER NOT NULL REFERENCES provincias(id),
    canton_id INTEGER NOT NULL REFERENCES cantones(id),
    parroquia_id INTEGER NOT NULL REFERENCES parroquias(id),
    zona_id BIGINT NOT NULL REFERENCES zonas(id),
    dpa VARCHAR(15) NOT NULL UNIQUE,
    infraestructura_tipo_id INTEGER,
    nombre TEXT,
    direccion TEXT,
    longitud NUMERIC(15,12) DEFAULT 0,
    latitud NUMERIC(15,12) DEFAULT 0,
    activo BOOLEAN DEFAULT TRUE,
    creador TEXT,
    creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modificador TEXT,
    modificacion TIMESTAMP,
    CONSTRAINT ck_infraestructuras_id_dpa CHECK (id = dpa::BIGINT)
);
