BEGIN;

CREATE TABLE IF NOT EXISTS public.emergencias (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL
);

ALTER TABLE public.usuario_perfil_coe_dpa_mesa
    ADD COLUMN IF NOT EXISTS emergencia_id INTEGER;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'usuario_perfil_coe_dpa_mesa_emergencia_id_fkey'
    ) THEN
        ALTER TABLE public.usuario_perfil_coe_dpa_mesa
            ADD CONSTRAINT usuario_perfil_coe_dpa_mesa_emergencia_id_fkey
            FOREIGN KEY (emergencia_id)
            REFERENCES public.emergencias(id)
            NOT VALID;
    END IF;
END $$;

WITH selected_emergencia AS (
    SELECT id
    FROM public.emergencias
    ORDER BY id DESC
    LIMIT 1
)
UPDATE public.usuario_perfil_coe_dpa_mesa ux
SET emergencia_id = selected_emergencia.id
FROM selected_emergencia
WHERE ux.emergencia_id IS NULL;

COMMIT;
