ALTER TABLE IF EXISTS public.eventos
    ADD COLUMN IF NOT EXISTS infraestructura_id BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS afectacion_variable_id INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS longitud NUMERIC(15,12) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS latitud NUMERIC(15,12) DEFAULT 0,
    ADD COLUMN IF NOT EXISTS activo BOOLEAN DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS evento_id_redm INTEGER NOT NULL DEFAULT 0;
