BEGIN;

CREATE TABLE IF NOT EXISTS public.emergencias (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL
);

ALTER TABLE public.infraestructura_tipos
    ADD COLUMN IF NOT EXISTS emergencia_id INTEGER;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'infraestructura_tipos_emergencia_id_fkey'
    ) THEN
        ALTER TABLE public.infraestructura_tipos
            ADD CONSTRAINT infraestructura_tipos_emergencia_id_fkey
            FOREIGN KEY (emergencia_id)
            REFERENCES public.emergencias(id)
            NOT VALID;
    END IF;
END $$;

UPDATE public.infraestructura_tipos
SET emergencia_id = (SELECT id FROM public.emergencias LIMIT 1)
WHERE emergencia_id IS NULL
  AND (SELECT COUNT(*) FROM public.emergencias) = 1;

COMMIT;
