BEGIN;

CREATE TABLE IF NOT EXISTS public.afectacion_variable_registros (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emergencia_id INTEGER NOT NULL,
    provincia_id INTEGER NOT NULL,
    canton_id INTEGER NOT NULL,
    parroquia_id INTEGER NOT NULL,
    evento_id INTEGER NOT NULL,
    afectacion_variable_id INTEGER NOT NULL,
    cantidad INTEGER NOT NULL,
    costo INTEGER NOT NULL,
    activo BOOLEAN DEFAULT TRUE,
    creador TEXT,
    creacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    modificador TEXT,
    modificacion TIMESTAMP WITH TIME ZONE,
    evento_id_redm INTEGER NOT NULL DEFAULT 0,
    afectacion_id_redm INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public.afectacion_variable_registro_detalles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    afectacion_variable_registro_id INTEGER NOT NULL,
    infraestructura_id BIGINT NOT NULL,
    costo INTEGER NOT NULL,
    activo BOOLEAN DEFAULT TRUE,
    creador TEXT,
    creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modificador TEXT,
    modificacion TIMESTAMP
);

COMMIT;
