BEGIN;

CREATE TABLE IF NOT EXISTS public.emergencias (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.infraestructura_tipos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emergencia_id INTEGER REFERENCES public.emergencias(id),
    nombre TEXT NOT NULL,
    siglas TEXT,
    descripcion TEXT,
    activo BOOLEAN DEFAULT TRUE,
    creador TEXT,
    creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modificador TEXT,
    modificacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE public.infraestructura_tipos
    ADD COLUMN IF NOT EXISTS emergencia_id INTEGER;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'infraestructura_tipos_emergencia_id_fkey'
    ) THEN
        ALTER TABLE public.infraestructura_tipos
            ADD CONSTRAINT infraestructura_tipos_emergencia_id_fkey
            FOREIGN KEY (emergencia_id)
            REFERENCES public.emergencias(id)
            NOT VALID;
    END IF;
END $$;

ALTER TABLE public.infraestructuras
    ADD COLUMN IF NOT EXISTS infraestructura_tipo_id INTEGER;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'infraestructuras_infraestructura_tipo_id_fkey'
    ) THEN
        ALTER TABLE public.infraestructuras
            ADD CONSTRAINT infraestructuras_infraestructura_tipo_id_fkey
            FOREIGN KEY (infraestructura_tipo_id)
            REFERENCES public.infraestructura_tipos(id)
            NOT VALID;
    END IF;
END $$;

COMMIT;
